ifeq ($(BR2_PACKAGE_SLT_GPU_LIGHT), y)

SLT_GPU_LIGHT_VERSION = master
SLT_GPU_LIGHT_SITE = $(call github,Fruit-Pi,slt_gpu_light,$(SLT_GPU_LIGHT_VERSION))
SLT_GPU_LIGHT_LICENSE = Apache V2.0
SLT_GPU_LIGHT_LICENSE_FILES = NOTICE

SLT_GPU_LIGHT_INSTALL_STAGING = YES

SLT_GPU_LIGHT_CONF_OPTS += -S src

ifeq ($(BR2_PACKAGE_LIBDRM),y)
SLT_GPU_LIGHT_DEPENDENCIES += libdrm
SLT_GPU_LIGHT_CONF_OPTS += -Dlibdrm=true
endif

$(eval $(cmake-package))

endif
