RKIPC_VERSION = rk3588-linux-6.1-rkr6
RKIPC_SITE = $(call github,mixtile-rockchip,mixtile-sdk-linux-app-rkipc,$(RKIPC_VERSION))

RKIPC_LICENSE = ROCKCHIP
RKIPC_LICENSE_FILES = LICENSE

RKIPC_DEPENDENCIES = camera-engine-rkaiq wpa_supplicant freetype common_algorithm

ifeq ($(BR2_PACKAGE_RKIPC_RK3576), y)
    RKIPC_DEPENDENCIES += rkfsmk rockit rockchip-rga
    RKIPC_CONF_OPTS += -DCOMPILE_FOR_RK3576=ON
    RKIPC_CONF_OPTS += -DCOMPILE_FOR_BUILDROOT=ON
endif

ifeq ($(BR2_PACKAGE_RKIPC_RK3576_MULTI_IPC), y)
    RKIPC_DEPENDENCIES += rkfsmk rockit rockchip-rga
    RKIPC_CONF_OPTS += -DCOMPILE_FOR_RK3576_MULTI_IPC=ON
    RKIPC_CONF_OPTS += -DCOMPILE_FOR_BUILDROOT=ON
endif

ifeq ($(BR2_PACKAGE_RKIPC_RK3588), y)
    RKIPC_DEPENDENCIES += rkfsmk rockit rockchip-rga
    RKIPC_CONF_OPTS += -DCOMPILE_FOR_RK3588=ON
    RKIPC_CONF_OPTS += -DCOMPILE_FOR_BUILDROOT=ON
endif

ifeq ($(BR2_PACKAGE_RKIPC_RK3588_MULTI_IPC), y)
    RKIPC_DEPENDENCIES += rkfsmk rockit rockchip-rga
    RKIPC_CONF_OPTS += -DCOMPILE_FOR_RK3588_MULTI_IPC=ON
    RKIPC_CONF_OPTS += -DCOMPILE_FOR_BUILDROOT=ON
endif

ifeq ($(BR2_PACKAGE_RKIPC_RV1126), y)
    RKIPC_DEPENDENCIES += camera-engine-rkaiq rkfsmk
    RKIPC_CONF_OPTS += -DCOMPILE_FOR_RV1126_RKMEDIA=ON
endif

ifeq ($(BR2_PACKAGE_RKIPC_RV1126_BATTERY_IPC), y)
	RKIPC_DEPENDENCIES += rockit rktoolkit
	RKIPC_CONF_OPTS += -DCOMPILE_FOR_RV1126_BATTERY_IPC=ON
endif

$(eval $(cmake-package))
